// Go Gopher — pixel adaptation for GoRunner.
// The Go gopher was designed by Renée French and is licensed under CC BY 4.0
// (https://creativecommons.org/licenses/by/4.0/). Changes: redrawn as an 18-cell-tall pixel sprite with a run cycle.
// The Go logo is not used. GoRunner is not affiliated with or endorsed by the Go project or Google.

import GoRunnerCore

extension RunnerArtCatalog {
    /// Light-blue bean body, big eyes, beige muzzle with buck teeth, beige feet and hands.
    /// 6 frames, 20×18 cells.
    static let gopher = PixelSprite(
        id: "gopher",
        names: ["ko": "고퍼", "en": "Go Gopher"],
        palette: [
            "o": 0x2F8C9AFF, // outline
            "G": 0x6AD7E5FF, // body
            "m": 0xF6D2A2FF, // muzzle, near foot, hands
            "M": 0xC6A677FF, // far foot
            "W": 0xFFFFFFFF, // eyes, teeth
            "K": 0x1A1A1AFF, // pupils, nose
        ],
        frames: [
            [ // 0: contact A
                "....................",
                "...oo.ooooooooo.oo..",
                "...oGoGGGGGGGGGoGo..",
                "...ooGGGGGGGGGGGoo..",
                "....oGGWWGGGWWGGo...",
                "....oGWWWWGWWWWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGGWWmKmWWGGo...",
                "....oGGmmmmmmmGGo...",
                "....oGGGmmmmmGGGo...",
                "..moGGGGGGWGGGGGGo..",
                "...oGGGGGGGGGGGGGom.",
                "...oGGGGGGGGGGGGGo..",
                "....oGGGGGGGGGGGo...",
                ".....ooooooooooo....",
                ".....MM......mm.....",
                "....MMM......mmm....",
            ],
            [ // 1: down A
                "....................",
                "....................",
                "...oo.ooooooooo.oo..",
                "...oGoGGGGGGGGGoGo..",
                "...ooGGGGGGGGGGGoo..",
                "....oGGWWGGGWWGGo...",
                "....oGWWWWGWWWWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGGWWmKmWWGGo...",
                "....oGGmmmmmmmGGo...",
                "....oGGGmmmmmGGGo...",
                "..moGGGGGGWGGGGGGom.",
                "...oGGGGGGGGGGGGGo..",
                "...oGGGGGGGGGGGGGo..",
                "....oGGGGGGGGGGGo...",
                ".....ooooooooooo....",
                "......MMM..mmm......",
            ],
            [ // 2: up A
                "...oo.ooooooooo.oo..",
                "...oGoGGGGGGGGGoGo..",
                "...ooGGGGGGGGGGGoo..",
                "....oGGWWGGGWWGGo...",
                "....oGWWWWGWWWWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGGWWmKmWWGGo...",
                "....oGGmmmmmmmGGo...",
                "....oGGGmmmmmGGGo...",
                "..moGGGGGGWGGGGGGom.",
                "...oGGGGGGGGGGGGGo..",
                "...oGGGGGGGGGGGGGo..",
                "....oGGGGGGGGGGGo...",
                ".....ooooooooooo....",
                "......mm....MMM.....",
                ".....mm.............",
                "....................",
            ],
            [ // 3: contact B
                "....................",
                "...oo.ooooooooo.oo..",
                "...oGoGGGGGGGGGoGo..",
                "...ooGGGGGGGGGGGoo..",
                "....oGGWWGGGWWGGo...",
                "....oGWWWWGWWWWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGGWWmKmWWGGo...",
                "....oGGmmmmmmmGGo...",
                "....oGGGmmmmmGGGo...",
                "...oGGGGGGWGGGGGGom.",
                "..moGGGGGGGGGGGGGo..",
                "...oGGGGGGGGGGGGGo..",
                "....oGGGGGGGGGGGo...",
                ".....ooooooooooo....",
                ".....mm......MM.....",
                "....mmm......MMM....",
            ],
            [ // 4: down B
                "....................",
                "....................",
                "...oo.ooooooooo.oo..",
                "...oGoGGGGGGGGGoGo..",
                "...ooGGGGGGGGGGGoo..",
                "....oGGWWGGGWWGGo...",
                "....oGWWWWGWWWWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGGWWmKmWWGGo...",
                "....oGGmmmmmmmGGo...",
                "....oGGGmmmmmGGGo...",
                "..moGGGGGGWGGGGGGom.",
                "...oGGGGGGGGGGGGGo..",
                "...oGGGGGGGGGGGGGo..",
                "....oGGGGGGGGGGGo...",
                ".....ooooooooooo....",
                "......mmm..MMM......",
            ],
            [ // 5: up B
                "...oo.ooooooooo.oo..",
                "...oGoGGGGGGGGGoGo..",
                "...ooGGGGGGGGGGGoo..",
                "....oGGWWGGGWWGGo...",
                "....oGWWWWGWWWWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGWWKWGWWKWGo...",
                "....oGGWWmKmWWGGo...",
                "....oGGmmmmmmmGGo...",
                "....oGGGmmmmmGGGo...",
                "..moGGGGGGWGGGGGGom.",
                "...oGGGGGGGGGGGGGo..",
                "...oGGGGGGGGGGGGGo..",
                "....oGGGGGGGGGGGo...",
                ".....ooooooooooo....",
                "......MM....mmm.....",
                ".....MM.............",
                "....................",
            ],
        ],
        isTemplate: false,
        credit: "Go gopher by Renée French, CC BY 4.0 — pixel adaptation for go-runner",
        license: "CC-BY-4.0",
        tags: ["mascot", "go", "animal"]
    )
}
