// Kodee — pixel adaptation of the Kotlin mascot for GoRunner.
// Kodee by JetBrains s.r.o. is licensed under CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).
// Changes: redrawn as an 18-cell-tall pixel sprite with a run cycle. Source: https://kotlinfoundation.org/guidelines/
// Kotlin is a trademark of JetBrains. GoRunner is not affiliated with or endorsed by JetBrains.

import GoRunnerCore

extension RunnerArtCatalog {
    /// Purple notched-top body, black visor with ring eyes and smile, thin limbs.
    /// 6 frames, 24×18 cells.
    static let kodee = PixelSprite(
        id: "kodee",
        names: ["ko": "코디", "en": "Kodee"],
        palette: [
            "k": 0x4527B8FF, // outline
            "P": 0x7F52FFFF, // body, near limbs
            "d": 0x5A36D6FF, // far leg
            "B": 0x000000FF, // visor
            "W": 0xFFFFFFFF, // eyes, smile
        ],
        frames: [
            [ // 0: contact A
                "........................",
                ".....kkk........kkk.....",
                ".....kPPkk....kkPPk..P..",
                ".....kPPPPkkkkPPPPk..P..",
                ".....kPBBBBBBBBBBPk..P..",
                ".....kPBWWWBBWWWBPk.P...",
                "....PkPBWBWBBWBWBPkP....",
                "...P.kPBWWWBBWWWBPk.....",
                "...P.kPBBBBWWBBBBPk.....",
                "..P..kPBBBBBBBBBBPk.....",
                ".....kPPPPPPPPPPPPk.....",
                "......kkkkkkkkkkkk......",
                "..........d..P..........",
                ".........d....P.........",
                "........d......P........",
                "........d......P........",
                ".......d........P.......",
                "......dd........PP......",
            ],
            [ // 1: down A
                "........................",
                "........................",
                ".....kkk........kkk.....",
                ".....kPPkk....kkPPk.....",
                ".....kPPPPkkkkPPPPk.....",
                ".....kPBBBBBBBBBBPk.....",
                ".....kPBWWWBBWWWBPk.....",
                "....PkPBWBWBBWBWBPkP....",
                "..PP.kPBWWWBBWWWBPk.PP..",
                ".....kPBBBBWWBBBBPk.....",
                ".....kPBBBBBBBBBBPk.....",
                ".....kPPPPPPPPPPPPk.....",
                "......kkkkkkkkkkkk......",
                "..........d..P..........",
                "........dd...P..........",
                ".......d......P.........",
                "......d.......P.........",
                "..............PP........",
            ],
            [ // 2: up A
                ".....kkk........kkk.....",
                ".....kPPkk....kkPPk.....",
                ".....kPPPPkkkkPPPPk.....",
                ".....kPBBBBBBBBBBPk.....",
                ".....kPBWWWBBWWWBPk.....",
                "....PkPBWBWBBWBWBPkP....",
                "..PP.kPBWWWBBWWWBPk.PP..",
                ".....kPBBBBWWBBBBPk.....",
                ".....kPBBBBBBBBBBPk.....",
                ".....kPPPPPPPPPPPPk.....",
                "......kkkkkkkkkkkk......",
                "..........d..P..........",
                "...........dP...........",
                "...........Pd...........",
                "...........P.d..........",
                "..........P..dd.........",
                ".........PP.............",
                "........................",
            ],
            [ // 3: contact B
                "........................",
                ".....kkk........kkk.....",
                "..P..kPPkk....kkPPk.....",
                "..P..kPPPPkkkkPPPPk.....",
                "..P..kPBBBBBBBBBBPk.....",
                "...P.kPBWWWBBWWWBPk.....",
                "....PkPBWBWBBWBWBPkP....",
                ".....kPBWWWBBWWWBPk.P...",
                ".....kPBBBBWWBBBBPk.P...",
                ".....kPBBBBBBBBBBPk..P..",
                ".....kPPPPPPPPPPPPk.....",
                "......kkkkkkkkkkkk......",
                "..........d..P..........",
                "...........dP...........",
                "...........Pd...........",
                "...........Pd...........",
                "..........P..d..........",
                ".........PP..dd.........",
            ],
            [ // 4: down B
                "........................",
                "........................",
                ".....kkk........kkk.....",
                ".....kPPkk....kkPPk.....",
                ".....kPPPPkkkkPPPPk.....",
                ".....kPBBBBBBBBBBPk.....",
                ".....kPBWWWBBWWWBPk.....",
                "....PkPBWBWBBWBWBPkP....",
                "..PP.kPBWWWBBWWWBPk.PP..",
                ".....kPBBBBWWBBBBPk.....",
                ".....kPBBBBBBBBBBPk.....",
                ".....kPPPPPPPPPPPPk.....",
                "......kkkkkkkkkkkk......",
                "..........d..P..........",
                "..........dPP...........",
                "..........Pd............",
                ".........P.d............",
                "...........dd...........",
            ],
            [ // 5: up B
                ".....kkk........kkk.....",
                ".....kPPkk....kkPPk.....",
                ".....kPPPPkkkkPPPPk.....",
                ".....kPBBBBBBBBBBPk.....",
                ".....kPBWWWBBWWWBPk.....",
                "....PkPBWBWBBWBWBPkP....",
                "..PP.kPBWWWBBWWWBPk.PP..",
                ".....kPBBBBWWBBBBPk.....",
                ".....kPBBBBBBBBBBPk.....",
                ".....kPPPPPPPPPPPPk.....",
                "......kkkkkkkkkkkk......",
                "..........d..P..........",
                ".........d....P.........",
                "........d......P........",
                "........d.......P.......",
                ".......d........PP......",
                "......dd................",
                "........................",
            ],
        ],
        isTemplate: false,
        credit: "Kodee by JetBrains s.r.o., CC BY 4.0 — pixel adaptation for go-runner",
        license: "CC-BY-4.0",
        tags: ["mascot", "kotlin"]
    )
}
