// Tux — pixel adaptation of the Linux penguin for GoRunner.
// Tux by Larry Ewing (lewing@isc.tamu.edu) and The GIMP. Use and modification permitted with acknowledgement.
// GoRunner is not affiliated with or endorsed by the Linux Foundation.

import GoRunnerCore

extension RunnerArtCatalog {
    /// Black penguin with white belly and face, yellow beak and feet, waddle-run.
    /// 6 frames, 20×18 cells.
    static let tux = PixelSprite(
        id: "tux",
        names: ["ko": "턱스", "en": "Tux"],
        palette: [
            "k": 0x232329FF, // body
            "o": 0x6E6E7AFF, // light rim (reads on dark menu bars)
            "W": 0xF5F5F5FF, // belly, eyes
            "K": 0x111111FF, // pupils
            "Y": 0xF7B81BFF, // beak, near foot
            "y": 0xC27A0AFF, // beak shade, soles, far foot
        ],
        frames: [
            [ // 0: contact A
                "....................",
                "........oooo........",
                ".......okkkko.......",
                "......okkkkkko......",
                "......okkWkWWo......",
                "......okkWkKWo......",
                "......okkkYYYYo.....",
                ".....okkkkyYYo......",
                ".....okkWWWWko......",
                "....ookkWWWWWko.....",
                "....okkWWWWWWWko....",
                "...okkkWWWWWWWko....",
                "..okokkWWWWWWWko....",
                "..oookkkWWWWWko.....",
                ".....okkkWWWko......",
                "......ooooooo.......",
                ".....yyy...YYY......",
                ".....yyyy..yyyy.....",
            ],
            [ // 1: down A
                "....................",
                "....................",
                "........oooo........",
                ".......okkkko.......",
                "......okkkkkko......",
                "......okkWkWWo......",
                "......okkWkKWo......",
                "......okkkYYYYo.....",
                ".....okkkkyYYo......",
                ".....okkWWWWko......",
                "....ookkWWWWWko.....",
                "....okkWWWWWWWko....",
                "....okkWWWWWWWko....",
                "....okoWWWWWWWko....",
                "....ookkWWWWWko.....",
                ".....okkkWWWko......",
                ".....yooooooo.......",
                ".........yyyy.......",
            ],
            [ // 2: up A
                "........oooo........",
                ".......okkkko.......",
                "......okkkkkko......",
                "......okkWkWWo......",
                "......okkWkKWo......",
                "......okkkYYYYo.....",
                ".....okkkkyYYo......",
                ".....okkWWWWko......",
                "....ookkWWWWWko.....",
                "....ookkWWWWWWko....",
                "....ookkWWWWWWko....",
                "....ookkWWWWWWko....",
                "....okooWWWWWko.....",
                ".....okkkWWWko......",
                "......ooooooo.......",
                "......YYY.yyyy......",
                "......yyyy..........",
                "....................",
            ],
            [ // 3: contact B
                "....................",
                "........oooo........",
                ".......okkkko.......",
                "......okkkkkko......",
                "......okkWkWWo......",
                "......okkWkKWo......",
                "......okkkYYYYo.....",
                ".....okkkkyYYo......",
                ".....okkWWWWko......",
                "....ookkWWWWWko.....",
                "....ookkWWWWWWko....",
                "....ookkWWWWWWko....",
                "....ookkWWWWWWko....",
                "....okooWWWWWko.....",
                ".....okkkWWWko......",
                "......ooooooo.......",
                ".....YYY...yyy......",
                ".....yyyy..yyyy.....",
            ],
            [ // 4: down B
                "....................",
                "....................",
                "........oooo........",
                ".......okkkko.......",
                "......okkkkkko......",
                "......okkWkWWo......",
                "......okkWkKWo......",
                "......okkkYYYYo.....",
                ".....okkkkyYYo......",
                ".....okkWWWWko......",
                "....ookkWWWWWko.....",
                "....okkWWWWWWWko....",
                "....okkWWWWWWWko....",
                "....okoWWWWWWWko....",
                "....ookkWWWWWko.....",
                ".....okkkWWWko......",
                ".....Yooooooo.......",
                ".....yyyy...........",
            ],
            [ // 5: up B
                "........oooo........",
                ".......okkkko.......",
                "......okkkkkko......",
                "......okkWkWWo......",
                "......okkWkKWo......",
                "......okkkYYYYo.....",
                ".....okkkkyYYo......",
                ".....okkWWWWko......",
                "....ookkWWWWWko.....",
                "....okkWWWWWWWko....",
                "...okkkWWWWWWWko....",
                "..okokkWWWWWWWko....",
                "..oookkkWWWWWko.....",
                ".....okkkWWWko......",
                "......ooooooo.......",
                "......yyyyYYY.......",
                "..........yyyy......",
                "....................",
            ],
        ],
        isTemplate: false,
        credit: "Tux by Larry Ewing and The GIMP — pixel adaptation for go-runner",
        license: "Tux-permissive",
        tags: ["mascot", "linux", "animal"]
    )
}
