import Foundation
import GoRunnerCore

enum StatuslineHook {
    static let scriptName = "claude-statusline.sh"
    static let previousCommandName = "claude-statusline-previous-command"
    static let previousObjectBackupName = "claude-statusline-previous.json"

    static func isHookCommand(_ command: String?, marker: String) -> Bool {
        command?.contains(marker) ?? false
    }

    /// Single-quotes a value for POSIX sh (`'` → `'\''`).
    static func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    /// POSIX sh hook. Writes the JSON first (Claude Code cancels an in-flight script when a new update
    /// arrives), then execs the previous command with the same stdin and returns its exit status.
    static func script(statuslineFile: URL, previousCommandFile: URL) -> String {
        """
        #!/bin/sh
        # go-runner Claude Code statusline hook (generated by go-runner, removed by its uninstaller).
        # 1) Saves the statusline JSON from stdin for go-runner (temp file + mv, so readers never see a partial file).
        # 2) Runs the previous statusLine command with the same input so its output is unchanged.
        out=\(shellQuote(statuslineFile.path))
        prev=\(shellQuote(previousCommandFile.path))
        input=$(cat)
        if [ -n "$input" ] && [ -d "${out%/*}" ]; then
          tmp="$out.$$.tmp"
          if printf '{"receivedAt":%s,"payload":%s}\\n' "$(date +%s)" "$input" > "$tmp" 2>/dev/null; then
            mv -f "$tmp" "$out" 2>/dev/null || rm -f "$tmp" 2>/dev/null
          else
            rm -f "$tmp" 2>/dev/null
          fi
        fi
        if [ -s "$prev" ]; then
          printf '%s\\n' "$input" | /bin/sh -c "$(cat "$prev")"
          exit $?
        fi
        exit 0

        """
    }
}

enum StatuslineInstallerError: LocalizedError {
    case settingsNotJSONObject(String)

    var errorDescription: String? {
        switch self {
        case .settingsNotJSONObject(let path):
            Loc.t("\(path) 파일이 올바른 JSON 객체가 아니어서 수정하지 않았습니다", "\(path) is not a valid JSON object, so it was left unchanged")
        }
    }
}

struct StatuslineInstallation {
    let installer: ClaudeStatuslineInstaller
    var now = Date()

    private var fileManager: FileManager { .default }

    var isInstalled: Bool {
        StatuslineHook.isHookCommand(Self.command(in: try? readSettings()), marker: installer.commandMarker)
    }

    static func command(in settings: [String: Any]?) -> String? {
        (settings?["statusLine"] as? [String: Any])?["command"] as? String
    }

    /// nil when the file is missing or blank. Throws when it exists but is not a JSON object (never overwrite it then).
    func readSettings() throws -> [String: Any]? {
        guard let data = fileManager.contents(atPath: installer.claudeSettingsURL.path) else { return nil }
        if String(decoding: data, as: UTF8.self).trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return nil }
        guard let object = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any] else {
            throw StatuslineInstallerError.settingsNotJSONObject(installer.claudeSettingsURL.path)
        }
        return object
    }

    func install() throws {
        for directory in [installer.binDirectory, installer.backupsDirectory,
                          installer.statuslineFile.deletingLastPathComponent(),
                          installer.claudeSettingsURL.deletingLastPathComponent()] {
            try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)
        }

        var settings = try readSettings() ?? [:]
        if let original = fileManager.contents(atPath: installer.claudeSettingsURL.path) {
            try backupFullSettings(original)
        }

        let previous = settings["statusLine"]
        let previousObject = previous as? [String: Any]
        let alreadyInstalled = StatuslineHook.isHookCommand(previousObject?["command"] as? String, marker: installer.commandMarker)

        if !alreadyInstalled {
            // Exactly what uninstall (and scripts/uninstall.sh) restores.
            let backup: Data
            if let previous, !(previous is NSNull) {
                backup = try JSONSerialization.data(withJSONObject: previous,
                                                    options: [.prettyPrinted, .withoutEscapingSlashes, .fragmentsAllowed])
            } else {
                backup = Data("null".utf8)
            }
            try backup.write(to: installer.previousStatusLineBackupURL, options: .atomic)
            let previousCommand = previousObject?["command"] as? String ?? ""
            try Data(previousCommand.utf8).write(to: installer.previousCommandURL, options: .atomic)
        } else if !fileManager.fileExists(atPath: installer.previousCommandURL.path) {
            try Data().write(to: installer.previousCommandURL, options: .atomic)
        }

        let script = StatuslineHook.script(statuslineFile: installer.statuslineFile, previousCommandFile: installer.previousCommandURL)
        try Data(script.utf8).write(to: installer.hookScriptURL, options: .atomic)
        try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: installer.hookScriptURL.path)

        var statusLine: [String: Any] = [
            "type": "command",
            "command": StatuslineHook.shellQuote(installer.hookScriptURL.path),
        ]
        for key in ["refreshInterval", "padding"] {
            if let value = previousObject?[key] { statusLine[key] = value }
        }
        settings["statusLine"] = statusLine
        try writeSettings(settings)
    }

    func uninstall() throws {
        guard let current = try? readSettings(),
              StatuslineHook.isHookCommand(Self.command(in: current), marker: installer.commandMarker) else { return }
        var settings = current
        if let data = fileManager.contents(atPath: installer.previousStatusLineBackupURL.path),
           let previous = try? JSONSerialization.jsonObject(with: data, options: .fragmentsAllowed),
           !(previous is NSNull) {
            settings["statusLine"] = previous
        } else {
            settings.removeValue(forKey: "statusLine")
        }
        try writeSettings(settings)
        for url in [installer.hookScriptURL, installer.previousCommandURL, installer.statuslineFile] {
            try? fileManager.removeItem(at: url)
        }
    }

    private func backupFullSettings(_ data: Data) throws {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyyMMdd-HHmmss"
        let stamp = formatter.string(from: now)
        var url = installer.backupsDirectory.appendingPathComponent("claude-settings-\(stamp).json")
        var suffix = 2
        while fileManager.fileExists(atPath: url.path) {
            url = installer.backupsDirectory.appendingPathComponent("claude-settings-\(stamp)-\(suffix).json")
            suffix += 1
        }
        try data.write(to: url, options: .withoutOverwriting)
    }

    private func writeSettings(_ settings: [String: Any]) throws {
        var data = try JSONSerialization.data(withJSONObject: settings, options: [.prettyPrinted, .withoutEscapingSlashes])
        data.append(0x0A)
        // Write through a symlinked settings.json (dotfile managers) instead of replacing the link.
        try data.write(to: installer.claudeSettingsURL.resolvingSymlinksInPath(), options: .atomic)
    }
}
