import Foundation

// Agent finish notifications — shared contract.
//
//   Claude Code  ── Stop hook ──────────────▶ gorunner-agent-event claude stop          (payload JSON on stdin)
//   Codex        ── notify ─▶ gorunner-codex-notify ─▶ gorunner-agent-event codex turn-complete <payload JSON>
//                                            └───▶ exec <previous notify program> <original args>
//   gorunner-agent-event appends one line to AppPaths.agentEventsFile; GoRunner watches that file and posts a notification.
//
// Privacy: only provider, event name, the working directory's folder name and a timestamp are recorded.
// Prompts, assistant messages and transcript paths are never written.

public enum AgentKind: String, Codable, Sendable, CaseIterable {
    case claude, codex

    public var displayName: String {
        switch self {
        case .claude: "Claude"
        case .codex: "Codex"
        }
    }
}

public struct AgentEvent: Codable, Sendable, Equatable {
    public var provider: AgentKind
    /// "stop" (Claude), "turn-complete" (Codex).
    public var event: String
    /// Last path component of the agent's working directory, if known.
    public var project: String?
    public var timestamp: Date

    public init(provider: AgentKind, event: String, project: String?, timestamp: Date) {
        self.provider = provider
        self.event = event
        self.project = project
        self.timestamp = timestamp
    }
}

public enum AgentEventLog {
    public static let recorderName = "gorunner-agent-event"
    /// Marker used by installers and scripts/uninstall.sh to recognize GoRunner-installed hooks.
    public static let hookMarker = "GoRunner/bin/gorunner-agent-event"

    public static func recorderURL(binDirectory: URL = AppPaths.binDirectory) -> URL {
        binDirectory.appendingPathComponent(recorderName)
    }

    /// POSIX sh recorder. Usage: `gorunner-agent-event <claude|codex> <event> [payload-json]`.
    /// Without a payload argument it reads stdin (Claude Code hooks). Always exits 0 and never blocks the agent.
    public static func recorderScript(eventsFile: URL = AppPaths.agentEventsFile) -> String {
        let out = shellSingleQuoted(eventsFile.path)
        return """
        #!/bin/sh
        # go-runner agent event recorder (generated by go-runner, removed by its uninstaller).
        # Records provider, event, project folder name and time only. Never records prompts or messages.
        out=\(out)
        provider="$1"
        event="$2"
        if [ $# -ge 3 ]; then payload="$3"; else payload=$(cat); fi
        [ -d "${out%/*}" ] || exit 0
        cwd=$(printf '%s' "$payload" | tr -d '\\n' | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
        project=""
        [ -n "$cwd" ] && project=$(basename "$cwd" 2>/dev/null)
        esc() { printf '%s' "$1" | sed 's/\\\\/\\\\\\\\/g; s/"/\\\\"/g'; }
        printf '{"provider":"%s","event":"%s","project":"%s","timestamp":%s}\\n' \\
          "$(esc "$provider")" "$(esc "$event")" "$(esc "$project")" "$(date +%s)" >> "$out" 2>/dev/null
        exit 0

        """
    }

    /// Writes the recorder script (0755) and returns its URL. Idempotent.
    @discardableResult
    public static func installRecorder(binDirectory: URL = AppPaths.binDirectory,
                                       eventsFile: URL = AppPaths.agentEventsFile) throws -> URL {
        let fm = FileManager.default
        try fm.createDirectory(at: binDirectory, withIntermediateDirectories: true)
        try fm.createDirectory(at: eventsFile.deletingLastPathComponent(), withIntermediateDirectories: true)
        let url = recorderURL(binDirectory: binDirectory)
        try recorderScript(eventsFile: eventsFile).write(to: url, atomically: true, encoding: .utf8)
        try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
        return url
    }

    /// Parses one line written by the recorder. Returns nil for malformed lines.
    public static func parse(line: String) -> AgentEvent? {
        guard let data = line.trimmingCharacters(in: .whitespacesAndNewlines).data(using: .utf8), !data.isEmpty,
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let providerRaw = object["provider"] as? String, let provider = AgentKind(rawValue: providerRaw),
              let event = object["event"] as? String
        else { return nil }
        let seconds = (object["timestamp"] as? NSNumber)?.doubleValue ?? Date().timeIntervalSince1970
        let project = (object["project"] as? String).flatMap { $0.isEmpty ? nil : $0 }
        return AgentEvent(provider: provider, event: event, project: project, timestamp: Date(timeIntervalSince1970: seconds))
    }

    /// `'...'` quoting safe for sh, including paths with spaces ("Application Support") and single quotes.
    public static func shellSingleQuoted(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
