import Foundation
import GoRunnerCore

public enum CodexNotifyInstallerError: LocalizedError, Equatable {
    /// The top level of config.toml isn't valid TOML (1-based line).
    case invalidConfig(path: String, line: Int)
    /// The top-level `notify` value isn't an array of single-line strings.
    case notifyNotParsable(path: String, line: Int)
    /// `codex-notify-previous.json` exists but can't be read.
    case backupUnreadable(path: String)

    public var errorDescription: String? {
        switch self {
        case .invalidConfig(let path, let line):
            Loc.t("\(path) 파일의 \(line)번째 줄을 해석할 수 없어 수정하지 않았습니다",
                  "Couldn't parse line \(line) of \(path), so it was left unchanged")
        case .notifyNotParsable(let path, let line):
            Loc.t("\(path) 파일 \(line)번째 줄의 notify 값이 문자열 배열이 아니어서 수정하지 않았습니다",
                  "The notify value on line \(line) of \(path) is not a list of strings, so it was left unchanged")
        case .backupUnreadable(let path):
            Loc.t("백업 파일 \(path)을(를) 읽을 수 없어 Codex 설정을 수정하지 않았습니다",
                  "Couldn't read the backup file \(path), so the Codex config was left unchanged")
        }
    }
}

/// Generated `gorunner-codex-notify` script.
enum CodexNotifyWrapper {
    /// The recorder runs synchronously before `exec`: Codex spawns notify fire-and-forget (it never waits for the
    /// process), so the wrapper can't delay a turn, and the recorder only runs a few tiny commands, always exits 0 and
    /// has stdin/stdout/stderr detached. Running it first keeps events ordered and leaves no orphaned process behind.
    static func script(recorder: URL, previousArgv: [String]?) -> String {
        let q = AgentEventLog.shellSingleQuoted
        var lines = [
            "#!/bin/sh",
            "# go-runner Codex notify wrapper (generated by go-runner, removed by its uninstaller).",
            "# 1) Record the finished turn for go-runner (project folder name and time only).",
            "# 2) Run the previous notify program with the same arguments so it keeps working.",
            "last=''",
            "for last; do :; done",
            "\(q(recorder.path)) codex turn-complete \"$last\" </dev/null >/dev/null 2>&1 || true",
        ]
        if let argv = previousArgv, let program = argv.first, !program.isEmpty {
            lines.append("exec " + argv.map(q).joined(separator: " ") + " \"$@\"")
        } else {
            lines.append("exit 0")
        }
        return lines.joined(separator: "\n") + "\n"
    }
}

struct CodexNotifyInstallation {
    let installer: CodexNotifyInstaller
    var now = Date()

    private var fileManager: FileManager { .default }
    private var configPath: String { installer.codexConfigURL.path }

    var wrapperURL: URL { installer.binDirectory.appendingPathComponent(installer.wrapperName) }
    var previousLineBackupURL: URL {
        installer.backupsDirectory.appendingPathComponent(CodexNotifyInstaller.previousLineBackupName)
    }

    /// `notify = ["<wrapper>"]`
    var notifyLine: String {
        "notify = [\(CodexConfigTOML.basicString(wrapperURL.path))]"
    }

    // MARK: - State

    var isInstalled: Bool {
        guard let bytes = try? readConfig(), let top = try? CodexConfigTOML.scanTopLevel(bytes),
              let notify = top.notify else { return false }
        return referencesWrapper(bytes, notify)
    }

    func referencesWrapper(_ bytes: [UInt8], _ notify: CodexConfigTOML.Assignment) -> Bool {
        String(decoding: bytes[notify.valueStart..<notify.valueEnd], as: UTF8.self).contains(installer.wrapperName)
    }

    // MARK: - Install

    func install() throws {
        let original = try readConfig()
        let bytes = original ?? []
        let top = try scan(bytes)
        let alreadyInstalled = top.notify.map { referencesWrapper(bytes, $0) } ?? false

        // Work out everything (and fail) before writing anything.
        let previousLine: String?
        let writePreviousLineBackup: Bool
        if alreadyInstalled, fileManager.fileExists(atPath: previousLineBackupURL.path) {
            previousLine = try readPreviousLineBackup()
            writePreviousLineBackup = false
        } else if alreadyInstalled {
            previousLine = nil // The original is unknown; uninstall will remove the line.
            writePreviousLineBackup = true
        } else {
            previousLine = try top.notify.map { try exactText(bytes, $0.lineStart..<$0.lineEnd) }
            writePreviousLineBackup = true
        }
        let previousArgv = try previousLine.flatMap(parsePreviousArgv)

        let newConfig = replacingNotify(in: bytes, top: top, with: Array(notifyLine.utf8))

        let recorder = try AgentEventLog.installRecorder(binDirectory: installer.binDirectory, eventsFile: installer.eventsFile)
        try fileManager.createDirectory(at: installer.backupsDirectory, withIntermediateDirectories: true)

        if writePreviousLineBackup {
            let object: [String: Any] = ["line": previousLine ?? NSNull()]
            let data = try JSONSerialization.data(withJSONObject: object, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])
            try data.write(to: previousLineBackupURL, options: .atomic)
        }

        // Wrapper before config, so Codex never points at a missing script.
        try Data(CodexNotifyWrapper.script(recorder: recorder, previousArgv: previousArgv).utf8).write(to: wrapperURL, options: .atomic)
        try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: wrapperURL.path)

        guard newConfig != bytes || original == nil else { return }
        if let original { try backupFullConfig(original) }
        try writeConfig(newConfig)
    }

    /// Replaces the top-level notify statement with `line`, or inserts it before the first table (at the end when
    /// there are no tables). Every other byte is kept.
    func replacingNotify(in bytes: [UInt8], top: CodexConfigTOML.TopLevel, with line: [UInt8]) -> [UInt8] {
        if let notify = top.notify {
            return Array(bytes[..<notify.lineStart]) + line + Array(bytes[notify.lineEnd...])
        }
        let lineBreak = CodexConfigTOML.lineBreak(in: bytes)
        if let offset = top.insertionOffset {
            return Array(bytes[..<offset]) + line + lineBreak + Array(bytes[offset...])
        }
        if bytes.isEmpty { return line + lineBreak }
        if bytes.last == ASCII.lf { return bytes + line + lineBreak }
        return bytes + lineBreak + line
    }

    private func parsePreviousArgv(_ line: String) throws -> [String]? {
        let lineBytes = Array(line.utf8)
        let top: CodexConfigTOML.TopLevel
        do {
            top = try CodexConfigTOML.scanTopLevel(lineBytes)
        } catch {
            throw CodexNotifyInstallerError.notifyNotParsable(path: configPath, line: 1)
        }
        guard let notify = top.notify else { return nil }
        do {
            let argv = try CodexConfigTOML.parseStringArray(lineBytes, range: notify.valueStart..<notify.valueEnd)
            // Never exec ourselves (e.g. a hand-copied wrapper line).
            if let program = argv.first, program.contains(installer.wrapperName) { return nil }
            return argv
        } catch {
            throw CodexNotifyInstallerError.notifyNotParsable(path: configPath, line: 1)
        }
    }

    // MARK: - Uninstall

    func uninstall() throws {
        if let bytes = try readConfig() {
            let top = try scan(bytes)
            if let notify = top.notify, referencesWrapper(bytes, notify) {
                let previous = fileManager.fileExists(atPath: previousLineBackupURL.path) ? try readPreviousLineBackup() : nil
                let restored: [UInt8]
                if let previous {
                    restored = Array(bytes[..<notify.lineStart]) + Array(previous.utf8) + Array(bytes[notify.lineEnd...])
                } else {
                    restored = CodexConfigTOML.removingLine(from: bytes, start: notify.lineStart, end: notify.lineEnd)
                }
                try writeConfig(restored)
            }
        }
        for url in [wrapperURL, previousLineBackupURL] where fileManager.fileExists(atPath: url.path) {
            try fileManager.removeItem(at: url)
        }
    }

    // MARK: - Files

    /// nil when config.toml doesn't exist.
    func readConfig() throws -> [UInt8]? {
        guard fileManager.fileExists(atPath: configPath) else { return nil }
        return [UInt8](try Data(contentsOf: installer.codexConfigURL))
    }

    private func scan(_ bytes: [UInt8]) throws -> CodexConfigTOML.TopLevel {
        let top: CodexConfigTOML.TopLevel
        do {
            top = try CodexConfigTOML.scanTopLevel(bytes)
        } catch let error as CodexConfigTOML.ScanError {
            throw CodexNotifyInstallerError.invalidConfig(path: configPath,
                                                          line: CodexConfigTOML.lineNumber(of: error.offset, in: bytes))
        }
        if let notify = top.notify {
            do {
                _ = try CodexConfigTOML.parseStringArray(bytes, range: notify.valueStart..<notify.valueEnd)
            } catch {
                throw CodexNotifyInstallerError.notifyNotParsable(path: configPath,
                                                                  line: CodexConfigTOML.lineNumber(of: notify.valueStart, in: bytes))
            }
        }
        return top
    }

    private func exactText(_ bytes: [UInt8], _ range: Range<Int>) throws -> String {
        let slice = Array(bytes[range])
        let text = String(decoding: slice, as: UTF8.self)
        guard Array(text.utf8) == slice else {
            throw CodexNotifyInstallerError.invalidConfig(path: configPath, line: CodexConfigTOML.lineNumber(of: range.lowerBound, in: bytes))
        }
        return text
    }

    /// The saved original notify text, or nil for `{"line": null}`.
    func readPreviousLineBackup() throws -> String? {
        guard let data = fileManager.contents(atPath: previousLineBackupURL.path),
              let object = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
        else { throw CodexNotifyInstallerError.backupUnreadable(path: previousLineBackupURL.path) }
        switch object["line"] {
        case nil, is NSNull: return nil
        case let line as String: return line
        default: throw CodexNotifyInstallerError.backupUnreadable(path: previousLineBackupURL.path)
        }
    }

    private func backupFullConfig(_ data: [UInt8]) throws {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyyMMdd-HHmmss"
        let stamp = formatter.string(from: now)
        var url = installer.backupsDirectory.appendingPathComponent("codex-config-\(stamp).toml")
        var counter = 2
        while fileManager.fileExists(atPath: url.path) {
            url = installer.backupsDirectory.appendingPathComponent("codex-config-\(stamp)-\(counter).toml")
            counter += 1
        }
        try Data(data).write(to: url, options: .withoutOverwriting)
    }

    /// Atomic write to the symlink target (dotfile setups), keeping the file's permissions.
    private func writeConfig(_ bytes: [UInt8]) throws {
        let target = installer.codexConfigURL.resolvingSymlinksInPath()
        let permissions = (try? fileManager.attributesOfItem(atPath: target.path))?[.posixPermissions]
        try fileManager.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Data(bytes).write(to: target, options: .atomic)
        if let permissions {
            try? fileManager.setAttributes([.posixPermissions: permissions], ofItemAtPath: target.path)
        }
    }
}
